# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "master" do |master|
     master.vm.box = "chef/centos-7.0"
     master.vm.network "private_network", ip: "192.168.200.2"
     # master.vm.provision :hosts
  end

  config.vm.define "node" do |node|
     node.vm.box = "chef/centos-7.0"
     node.vm.network "private_network", ip: "192.168.200.3"
     # node.vm.provision :hosts
     # node.vm.network "private_network", type: "dhcp"
  end

  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.synced_folder "../../", "/kubernetes"

end
